### ISSUE TITLE
slice

### ISSUE THREAD

**Issue by LuisDaw** [LuisDaw/practica_dwec_gestor_presupuesto#2]
Buenas @pedroprieto estoy intentando hacer la primera funcion de agrupar y me da error de que ,slice no es una funcion.
He probado segun lo visto en los apuntes a crear una variable para no modificar la fecha, pero creo que no estoy introduciendo bien lo que es el dato de la fecha
Le adjunto el codigo por si quiere verlo por aqui mejor
`  this.obtenerPeriodoAgrupacion = function (periodo) {
            let aux = fecha;
            if (periodo == "dia") {
                aux = fecha.slice();
            }else if (periodo == "mes") {
                aux = fecha.slice(0, 7);
            }else if (periodo == "anyo") {
                aux = fecha.slice(0, 4)
            }
            return aux;
        }`
Gracias por todo

**Comment by pedroprieto** [comment]
Buenas,

El problema está en varios sitios.
- En primer lugar:
  https://github.com/LuisDaw/practica_dwec_gestor_presupuesto/blob/48647c2f76662cd233d136987cfc80636c6387fb/js/gestionPresupuesto.js#L99
  `fecha` no existe. Debes utilizar `this.fecha`, ya que es la propiedad del objeto.
- En segundo lugar, `this.fecha` es un número, un timestamp. Por tanto, no tiene el método `slice`. Antes tienes que transformarlo en un objeto `Date`, de ahí a string, y por último ejecutar `slice` sobre dicho string.

Un saludo!

**Comment by LuisRodes** [comment]
Ok lo intento gracias
